# Generated by Django 5.0.4 on 2024-06-22 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_inventory', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='telegram_id',
        ),
    ]
