# Generated by Django 5.0.4 on 2024-06-22 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_inventory', '0002_remove_customer_telegram_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='seller',
        ),
    ]
