# Generated by Django 5.0.4 on 2024-05-29 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_inventory', '0002_alter_products_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='debt',
            name='debt',
            field=models.DecimalField(decimal_places=2, max_digits=30),
        ),
    ]
