# Generated by Django 5.0.4 on 2024-05-27 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_inventory', '0002_alter_products_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producttype',
            name='seller',
        ),
    ]
