# Generated by Django 5.0.4 on 2024-05-29 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_inventory', '0003_alter_debt_debt'),
    ]

    operations = [
        migrations.RenameField(
            model_name='debt',
            old_name='debt',
            new_name='debt_amount',
        ),
    ]
