# Generated by Django 5.0.4 on 2024-05-29 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_inventory', '0006_alter_customer_telegram_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='telegram_id',
            field=models.IntegerField(),
        ),
    ]
